### GET request to example server
GET http://localhost:8080/persons

###
POST http://localhost:8080/persons
Content-Type: application/json

{
  "name": "Anna",
  "programmer": true
}

###
POST http://localhost:8080/persons/1/languages
Content-Type: application/json

{
  "languages": ["java","rust","english"]
}
